FROM quay.io/fedora/fedora-bootc:latest@sha256:860bf88894a545eef250cb442c87d1491165975d2f5c1e65a19fde5d26801dd6 AS bootc

FROM quay.io/fedora/fedora:latest@sha256:75bf3c17acf32fa40bd2323f8ea4eb241749627d8b14308a54925647d4bff1d3

ENV USERNAME="ublue"

COPY --from=bootc --chmod=0755 /usr/libexec/bootc-base-imagectl /usr/libexec/bootc-base-imagectl
COPY --from=bootc /usr/share/doc/bootc-base-imagectl /usr/share/doc/

COPY fedora-atomic.pub /staging/
COPY fedora-atomic.yaml /staging/
COPY policy.json /staging/

RUN --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
set -eoux pipefail
dnf5 config-manager setopt install_weak_deps=False
dnf5 copr -y enable ublue-os/packages

dnf5 install -y \
    ShellCheck \
    cpp \
    erofs-utils \
    golang-oras \
    just \
    openssl \
    python3 \
    rpm-ostree \
    systemd-container \
    selinux-policy-targeted \
    sbsigntools \
    shfmt \
    socat \
    tmux \
    ublue-os-signing \
    yq \
    zstd

# Copy files from the staging directory
cp /staging/fedora-atomic.pub /etc/pki/containers/
cp /staging/fedora-atomic.yaml /etc/containers/registries.d/
cp /staging/policy.json /usr/etc/containers/policy.json
cp /staging/policy.json /etc/containers/policy.json

# Clean up the staging directory
rm -rf /staging

# syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/bin

# cosign
while [[ -z "${COSIGN_VERSION:-}" ]]; do
    COSIGN_VERSION=$(curl https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d : -f2 | tr -d "v\", ") || (sleep 30)
done
dnf5 install -y "https://github.com/sigstore/cosign/releases/latest/download/cosign-${COSIGN_VERSION}-1.$(rpm -E %_arch).rpm"

# macadam
if [[ "$(rpm -E %_arch)" =~ x86_64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-amd64"
elif [[ "$(rpm -E %_arch)" =~ aarch64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-arm64"
else
    echo "Unsupported Arch" >&2
    exit 1
fi
chmod +x /usr/bin/macadam
macadam completion bash >/etc/bash_completion.d/macadam.sh

# bootc-base-imagectl
chmod +x /usr/libexec/bootc-base-imagectl

# Cleanup
dnf5 copr -y disable ublue-os/packages
dnf5 clean all
RUNEOF

LABEL \
    "name"="devcontainer" \
    "org.opencontainers.image.name"="devcontainer" \
    "org.opencontainers.image.url"="https://github.com/iitzrohan/devcontainer" \
    "org.opencontainers.image.vendor"="iitzrohan" \
    "org.opencontainers.image.version"="base" \
    "vendor"="iitzrohan" \
    "version"="base"
